services:
  postgres:
    image: postgres:17
    container_name: taxi-backend
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: taxi_backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  web:
    build: .
    image: taxi-backend-app
    ports: 
      - "3001:3000"
    environment: 
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/taxi_backend"
    depends_on:
      - postgres

volumes:
  postgres_data: